apiVersion: v1
kind: Secret
metadata:
    name: newt-site-a-auth
    namespace: newt
type: Opaque
stringData:
    PANGOLIN_ENDPOINT: ENC[AES256_GCM,data:AXe8DdYW0djmSPJ0u+8R+JMt1eBqr7XNldLQgPE=,iv:fBjQRHxh7Zjd7v08FrVCCsIV9q/cxzX68l0EsQZnzKM=,tag:IjlhBViZWc33NTDHEoANSA==,type:str]
    NEWT_ID: ENC[AES256_GCM,data:0sOzsdTQX7DR1x76STQy,iv:DMwk1n6eVSo/mC7gWT/X74maLzQ04cpCLJXjjz3wabQ=,tag:FserxJTnQohGCNpneoOgNw==,type:str]
    NEWT_SECRET: ENC[AES256_GCM,data:/85kc6NCr3XB/xvJpVhEyWr7cYRzC7cQdu1BV2iVDVjxW6nf0AIomJcrn/nrblqF,iv:r2aMBHNoCb7u7mEIwAEEnZHmtodXYpPteLUgFA2GAFc=,tag:nOSQEUsY6zpIIghOmwlirg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKMEhJT2w1ZW10Z1NHdGN3
            K0lXZUNSd3hiS3lTY1Q0dXM2bnhVaUxCR2owCjQwY3lRWFlFSTlvTEpaeld5TW54
            NWNGeHBhRFdHWXdGNUk4N1dtYjBUYkEKLS0tIFRUWmZpblVHU25oQTltZjd1Mmlq
            L1kyTnlBbFJkTXJidU95Qi9odUpKamMKe2a48Ts/yAx31jLOx0K3pMX+2VotbY6W
            bi/OhIqkiDWV0g4ghBBMA+oiSFMYZOUsJ4mR3nEzG9iEKDTfB1ZeLA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u897l89mkwn8jpwckjaln0fw50thp7mfs2c78cx0aw48slfyu5nsvvt4ft
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLbERWbHhPd3RxTUh0L2Vo
            bkZzaXVaMjJDZm5IRzZ1Y0M2YkJtWDJDeFJJCnlhUnJRckNOWnhKb08zWjgxK2dT
            aTlMd2pNZ3dCcFhNbm53TVFZMHVDZm8KLS0tIEpCdXlFcUVXdW9RZDRjeDhWUG50
            cEViTHNBWE9ncGVEbW03UTRuR2pjTFEKhm8eEvp2c8duqO6ecQjLcNT9wiT79WHD
            OhvJ/BnQ7/fo8DoO6+LuxJrJkMU/ZA58nSMcwK0hG0c9ZY37cLhquw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1gn97pnarxh3wkdv2l8ynk6s7ted0u5hgudhxyfec2djwy3dsapsss2ak8p
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwUkt6WW5iSDZhWVFZaS9D
            YTNKMW5BQ0xFZGtpRXUrTUxoNEdHdDBJNVRBCjlyY2kwU2QvcXhLYXFaUTNDRFkr
            SFdZcWlselkrU3ZwZURjWERkZ1crODAKLS0tIFFydFY2M1ZORTFLU0RUS1VieFhv
            T3U2SDVwRzNOUUo3dDlFMVhmanVCekkK0fFypDu46cXI9OrowlJXvMruQMIn+4rk
            liusWoF6jW47cqVLzJQcolfVmp3vA85GeqkfyHVEdDwdJXaj39i70g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1epz74rx38txrvhxxp4lq43lca6kg2yg0a5ay3pkhshfwgwx2dexsvj9vvz
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-10T20:50:14Z"
    mac: ENC[AES256_GCM,data:qCI0uw331lM1ZvXTJDIiuT/G4kcvPUiNHD79kEnbnzyG3c93+S03CmW4wbztkonenYlqAalWHQQKWCa5quhpIWyxd+IizXWwvnn0An79R6BlUC8Pc/7HinGIzzZFAOQJ//cmvkqU/UIitndEBDkBfrlMTtJktElwvHJ/vSGxCx4=,iv:CsVLUGTjrOnB8m4T3rcVZZt14+1NvfEEaYITL5ZPcKU=,tag:s+zWfuB0tRikR8eCdaQvDg==,type:str]
    version: 3.13.3
