apiVersion: v1
kind: Secret
metadata:
    name: newt-site-b-auth
    namespace: newt
type: Opaque
stringData:
    PANGOLIN_ENDPOINT: ENC[AES256_GCM,data:VJF3fWS7HHj9m7r0ruhf1tkpbBkUWekgpWJULnw=,iv:Ukk/SIe5L+hkoDohHjggGDeOpW21qUnojOJHD60ddvw=,tag:ABAn0BTvANtnuPjKJH11tg==,type:str]
    NEWT_ID: ENC[AES256_GCM,data:83/VEvh6hebMUSYZmSjF,iv:c/3JaL7jBA70KmlzWW6f9Cmyco4lrwOQWVhMy3evJwg=,tag:8wowMc0pbDwMyEpnBiXXeQ==,type:str]
    NEWT_SECRET: ENC[AES256_GCM,data:1lVQ4FGQJ/5WXYHfGLAO2F0e0xWyUdulmnA5aP8UM6jdYyir4eR1dxDTgfioDK1s,iv:iOoQP6UuyhkGtDzNeYvBgSAuRpI/TNZs126Xo2J921k=,tag:2POr7xpv34Bt5YAodvt0JA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2bUVHdkNpRFBPT1hjczI2
            V1o2ZGtleHBlWlFXb1lRQkZkMVAwQ25kczJBCjJxSS90d3RTUTg4Nlc1QnFncHln
            RXlnT2ZRUXFwcUtYZ3hMRWQ3K1lJMWcKLS0tIDdrM09sR0dJUG03eXFGWGZNRU4z
            UFBueklwcEx0WHJNWTVQdk9tZStvY1kKw9Z+dUkS0y3Dx3h6fsoDYTVaV8jda6cZ
            czulTmZdx/2bShndOB4G1qb0adOJrmlCjTvoOBI9gFXdzUd9puKyng==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u897l89mkwn8jpwckjaln0fw50thp7mfs2c78cx0aw48slfyu5nsvvt4ft
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpbTEvRUplem1JSng3TUFW
            Q09kZlJyU2pqcEVGM0VlZFN0alBBQStKWVZjCnpzU01kMEJHZmVrZjNEdWV2TW1h
            elM1TDN1ZEQwQldIZys1SkNlODBXazQKLS0tIFVYU25WbXhGVmNYMUN0Nm5RR2Yr
            S21zd0FVL0o4Ujd2MFVPbDBtc0NaTlUKWG9wOym3AQl30SmeAcUnjmh9F5eFPmsZ
            GvXa5SciIkjFBcYmnRGtscB4u0OxcN6iqFHYTZN1C0esCdaIOnuSZQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1gn97pnarxh3wkdv2l8ynk6s7ted0u5hgudhxyfec2djwy3dsapsss2ak8p
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPdW1GQUZrUGdaa2hpdzJo
            N2h0QUo1ZFBnbkhoVXFwSUxvSVpSaFVkcm0wCkhTc3RtSStQd3ZoU1ZjclVUUTFO
            d2V5d3NMS0hwK3AxeVNxSDZvYmFCWmsKLS0tIFREVjQwN1RnUmpZSDBCVkVjMXRi
            aWNkRTZvdFRGZjlHc2hZQyt4dG1zbFEKzEBYRTczep4J3HrWAREw90P7t4txSK3E
            FvpgjPvU6igaJ2FCbWA+KV5kbIaUItR51ihqWm/81X3imYQCBaAD+g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1epz74rx38txrvhxxp4lq43lca6kg2yg0a5ay3pkhshfwgwx2dexsvj9vvz
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-10T20:50:02Z"
    mac: ENC[AES256_GCM,data:/OjnYm+8CpsRoyh2oB8njpyRwcF9fJRY5cW2fp05k8u1pCA449jTuj9FrJ04X6FXi6DUzToStO5dFB7vByvjw4lUVnDSkd0UZvrqNjIOoPAypCVFbjse8DRC23+ljvZYKz+UFNc/HF6M/JHu3yjW5ixakmbAIskxrtlscKk8+Nc=,iv:FFU0e5MWD1C8OGsBZTIOmr3x8ESEiFBxIS8Y6O2Ayj0=,tag:JBdS2Pp4DCW+gTsBLdU8gw==,type:str]
    version: 3.13.3
