apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openwebui-mabel
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/d-kholin/k3s-hl.git
    targetRevision: HEAD
    path: apps/openwebui-mabel/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: openwebui-mabel
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - SkipDryRunOnMissingResource=true
    retry:
      limit: 5
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 5m
