apiVersion: v1
kind: Secret
metadata:
    name: openwebui-mabel-secrets
    namespace: openwebui-mabel
type: Opaque
stringData:
    #ENC[AES256_GCM,data:CUSAzwE2G6/bt8E1WCceMwwgxk/PZ7shXmXV/NXnTavP0uptvw27KbmsiG8H5ybwEondggerVUBrM8KpkTX3kwAnkKQeDUaL,iv:WZ7H1XSxyddFmsp2NXUW4xJKFNffLe3fSQwuuQIk4EM=,tag:DYnMJ70A6jvabfas9LSXEA==,type:comment]
    HERMES_API_KEY: ENC[AES256_GCM,data:YL5wrB7/6xMfG1Qa5vyBT/EAlLSfDRmHxK1rjMsxSPE=,iv:to7y/UQHD0Wz8JyQJ2/h66La908LcvPXsaWkVaKcWek=,tag:syd7RA6K3XD3Ed2V7AecEQ==,type:str]
    #ENC[AES256_GCM,data:5+oaSVT62qyeig91bcoVkA2E1QzUaD4DvBauO+oj+wxPdCgT,iv:PSKEcbr03UWw0IDgv0l6YOZ7f7CQyaVkit9B9nNLJG8=,tag:l07rC4Yz1S78GEmqnZ2K4A==,type:comment]
    WEBUI_SECRET_KEY: ENC[AES256_GCM,data:EYKRUXaacnmm0+ryGdJB1n+lqyY4xN1aDTx3OdkoKCg=,iv:Hoa8qStJRMYOvwGH6/Mn1deZ3UUx5D0Ayms/lhs7O8s=,tag:Fli2wA5dcPIHys3tkqNQzQ==,type:str]
    HERMES_API_BASE_URL: ENC[AES256_GCM,data:FYfBCV7wjUftmDc1QsS81gaKUd/nRWZlJ+UR,iv:HVnqZ/pB5IpDE0wcT7kYTd1C+hvD0FMFC2RvLFvXwdw=,tag:0Q7P9HBP3Bw3T6BgyQy8bg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4a1VqUERudlNYam0zOWdj
            dlFXTU8vWFExMlVyVHZ0QTBXdWgvVEFYbkJnCmlYU05sNkgwN0hCamdnN1JJaC8x
            UjJSaExTeWpuVHU3RmNLMThzUzZJWkUKLS0tIERnVUJuRGhRcURWV1hzZjNUbC9E
            d3pCb09ISlQyUjdPM2hpUGk0TUVWREEK8jK1WwxP8xpRXzppKqpHk2/0mHLFJmep
            Lt1YJCozs8xvhIItUGRt9kWl0PyimjuQcSrLJQZPZ+ZiC5RYswBj2g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u897l89mkwn8jpwckjaln0fw50thp7mfs2c78cx0aw48slfyu5nsvvt4ft
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRdFVKK25jNmVXeGM3a1FD
            QVI1Um1UZDcwbW0yckJsdExDcVVsR3ZRRUhVCjdtK21nQjg5ZjJOUE4rK1hLK01R
            ZkVQOHJHZW4zTFMzOEZSc3JxVWpNT2MKLS0tIElETkR0cGtwekk3SzdkN1c0V2ps
            bWFTWFZ4WW1zdkRLMzFJcS91Rnc1QWsKtXQGjZyV6S73ugTpJ1H+5SPJMzDw25M3
            yEeRu930DKAphoLnOgqrfrHVLcqsprCrPPBV18U2WMb3e0H6jZRJeA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1gn97pnarxh3wkdv2l8ynk6s7ted0u5hgudhxyfec2djwy3dsapsss2ak8p
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGQUNSaldxSFdiV21BL21j
            N2E2dTE4eWhlM1UyOEZZNmJIK3NtaEE3eUhFCkhUZEcxcC9UNmswVkxCWm5PZEhR
            dHQ1bUx4cEtJaHE0REh4eGVpcGNEMFEKLS0tIGpnQkNVWDhmZ0Z4emxQbkZ3UU1y
            NUlSV1cvRkJxWG1jUVJkZEdKVjR5alkKAP6F4mGlD/KMnbNepvMbFR/Kew6xDybO
            JQPubzNrhohebL+7pGAGMrROCcpmI8BKI71puwmJT0xWHTiwlQkBpg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1epz74rx38txrvhxxp4lq43lca6kg2yg0a5ay3pkhshfwgwx2dexsvj9vvz
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-20T22:44:40Z"
    mac: ENC[AES256_GCM,data:W3WPZ/if50GNXZ/Nv809EaY6jZyohd3OiZv3m2jeIpgOCU/1n1X1Tx7ANUpUkoFlRXJVEyoVF7jYR2qKyvzhca1koABxlieFv0Y7X8UIx8QsLnUJMb3EZNLfxLm4UkStphlG0az+QZh1HH29wXloArjmxUOalERPADT4lDx9Qag=,iv:xiy/aI40vDvEAS9e+m+9CPL6bqU4LTM+a9AhGQSjIXk=,tag:ZEs8IwgaVk6wMLov/6R1jA==,type:str]
    version: 3.13.3
