apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openwebui-mable-data-encrypted
  namespace: openwebui-mable
  annotations:
    argocd.argoproj.io/sync-options: Prune=false,Delete=false
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-encrypted
  resources:
    requests:
      storage: 10Gi
