apiVersion: v1
kind: Secret
metadata:
    name: openwebui-secrets
    namespace: openwebui
type: Opaque
stringData:
    #ENC[AES256_GCM,data:fDyNpZ2Nca3h/9Z5imJWjLeY8hflbLPMQ6XMXAKamOTlq5mKxSCg+TycaDNrlwCcx+cvsCYnrA/rMx0R+l5TfRW+,iv:Ms6eVSNM3aKIo/SbRvCakC9fNhR6rqeoAVsOR4u5tUI=,tag:LFcjFO9CLmtbAQQErO6Ukw==,type:comment]
    HERMES_API_KEY: ENC[AES256_GCM,data:QSdQFLi885fQI5VGeOEPM7EQow87q7AP7/ML22zxcTs=,iv:xZJ8MuGCoQCNvbvxpF8cnhhgdbRC9VCtWItETuD/MYQ=,tag:AJoJhM408aS8S62rQ2ZQ4A==,type:str]
    #ENC[AES256_GCM,data:yD66vQ4imr2bXmqdpuT304YhQUWMddl1ErC00XwZRNEeUINr,iv:n/+6JKtGPqrK1JVir0nupY4ciw7StFrTeY+tQ1t91do=,tag:XAQ8ZchZ6EVGaN8HwKcLKg==,type:comment]
    WEBUI_SECRET_KEY: ENC[AES256_GCM,data:i193thMSC6DZuacEP+diNJKw2TWm7nY2rkTYb5hZV7w=,iv:YpRIqv6qsVh9i/72aUd6hs2PSrpjDERi2ZSVdCmByzE=,tag:9p/X5ZCu2m93Eks7vvG0sg==,type:str]
    HERMES_API_BASE_URL: ENC[AES256_GCM,data:wt5plp20zjA1GraFt1zFRlecKYvsJwIlJKtb,iv:lQpoRjH5H99ZZSA2P5/JFTfo9fjjzVbcWLa2LpwA/uY=,tag:Uc5F/+kiW+fNFgJNegnkng==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIeThIaW1HUkVjWm43bWl6
            WnZzSlFPdGhlajNvZkNSeDMxME43dmw2V1ZJCmdPY0tqcjArdGFlcUxPbmFxS1BX
            Y09oWVpWdTVjeXpuWHNRTnA5OHY2SVkKLS0tIHZ5WnRGa3pDdnR3Mm14NDA5eE9C
            eWpJOWJFNk1mVDIveG5pc2lBbU10VmcK8vQ0rJ3A+lixZeLQ8hmRVwd6DjD2G8bq
            QXqqrvwKF9XzRnfCD4T2IG1XYSli9lKC8Dk7UQZKfeYKiTkJmKsD1g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u897l89mkwn8jpwckjaln0fw50thp7mfs2c78cx0aw48slfyu5nsvvt4ft
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuZTlFOGxtdERUL3lUeXdX
            SnRvTFVEUTlCakN3NzV1V2ErVWN6KzdvQncwCnI2OUdQams2cDJXdm51STk0UGla
            S2thQXY5QzRIYkNzdXhLVnY2RlQybG8KLS0tIGxaQTJGT211S3B6RWNPWmsrdWYr
            MTlZaytCUWJsV3NsdVF4M3NzNzlBL3MK6/2zTS2aDDOSbY2hzRBGHHe27YvlBKSR
            WC4CtoCrs1TkgrXgrjcbKOtuTBVEp+K008HYO57NsCzV6dAAsUsBfA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1gn97pnarxh3wkdv2l8ynk6s7ted0u5hgudhxyfec2djwy3dsapsss2ak8p
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoTDhYdXgwb3VlRHJRZHdw
            eGhWc2NnZVhST0lqLzI0RzNVS2s3cnZVc0VRCkFIU1BUdnZsYVA1N0xFVUR1MXZm
            UzAzWE4yeDZLdTkzd25ZWmJycC9xNkEKLS0tIE15S2xXRllkVG5rODNSQ29sR1M2
            cmU1TDR2RDNMTXU5VzAybEc4UkREWGcKLIeXGGbDQaDI3HY5FkW2DBy2wdhrG5Nw
            hlfAsWgsIiB7DxwKqwwqrVynqXKOjWHAk9PyGglhujnGFSrsD2A1Sw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1epz74rx38txrvhxxp4lq43lca6kg2yg0a5ay3pkhshfwgwx2dexsvj9vvz
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-20T21:56:50Z"
    mac: ENC[AES256_GCM,data:qTKwuyYgAa57D0kQxNwsxvsSJeQ7YdRdQ5P/p+5rkOZCKgxUPpjDiBF9kOGbG9fnkanyLBTdStxfMV1fbV/o4migj+BN9c6yfvZmjL5XekPH/jKsQn+Wu527iYFUxtmNCbTBDdq3z3H22wrnf0MOrqIdeADJZc//FOn7soq+bkg=,iv:coCQJPv3pVEMzx9SJvw/rns6Y0C9G7LGtDjL5TQK56o=,tag:Mv3O0qeDeHtlXl/j4ESNQw==,type:str]
    version: 3.13.3
