apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns-secrets
    namespace: cloudflare-ddns
type: Opaque
stringData:
    #ENC[AES256_GCM,data:GOAuLY5FvR+sMHAWJZnzdMBPzLuAuBl4uITtiSGjIzMreJ0gtzfPoDVFhbQPFazc/kUt,iv:UIVwaKf/6T6w74B8k84Ye45bvnG1XwfmdbvXoy7IGHg=,tag:UTr/t/4WdDBa8YdN1TAJNw==,type:comment]
    CLOUDFLARE_API_TOKEN: ENC[AES256_GCM,data:RKfDOwHO1q8qYOCHoRLeof1Hz8CymDnqknvU9l2bRD4g0ciGZ3OvoA==,iv:rcq/mGZhSoF687EzALIBC4AZhGBJq6l4jsLVRyCtAsM=,tag:ZaP5X6YFAcc3XbFq8+oAbQ==,type:str]
    #ENC[AES256_GCM,data:2n3F9udyAQc3bajydZpamJZUB/3s1H218XSx7tODhyk7RFM0YoU4o8Sc,iv:6M2Cg9Z52gy138iSynpKsJSSV1M4qAg4OUiLL4GznSY=,tag:87CS00kTAbx+H2H0GhJ3tw==,type:comment]
    DOMAINS: ENC[AES256_GCM,data:so8UIcco2DiiPSGYbfqghEjCqWqqjiw3p2c2RQUnrK2aBTfJQFXCWODVVFdLpVOvBwN/cHGSMgjnCjkNwZyBZWzLKtJE8QKzN0wTNE2WO+K/IkGo7EO0d/8E7umNZwJoboGbNBzXbso1tLF38qvRjZ3efOMHVNh0udHjkDuR4IOD/5G07cwG4cuwvpEEaTS9M4pYUVvO41w6XJbKE7pEtyYHNguneCDuBbVspvb6UkZoDFex3FbTVXK8PWccV0VLU+JC0/LvGzPm5WIvWhrNsvmLF2NGO6Fwn3hontouSczh1Z1k+kDm27GTlvMlYa6w9sC/p8PbNktMCw/TEBtXOBxkofYhK2QUnKKzoIqPqlxY1YozKS+BJqEqRCYgvd2TOeepviXQcQ8Dr1jRGoTad7PRqe+CBexlbWdL65TZ1+SONCdNADNSZlLlfxUT5THNX0OMHvxOYhBpA0cPsNrTDK0ZTWh1lGgnD4sXsoo0Q2gM4mOn8ZjO8QNKDyxxStBJzTAegCEWZBSUc/UJpQBTDxrwJGWSxiwKSl8WtaOnJ/XUaFsYfd0FTCKcIs+N1ay1CCF3JsgCC2rnGc2EQBCoGcss37Y1MdetruT4uLzxbbnDK3V8mO7ORHHor6jkbeWpiOaughcIaBAmnK65MJEGfjP0q02Sxbk0QInrPo1reMShQAgZbdYdA7/WssfC4E1+23CAvBF7mwiRKo8QQh6dG6l39hr5jDrSvWDTUnPQ24ZfI7OtBu10NbRmBVd0RUK8ZGQ1R710olysDnUBqe59OSGFAjQSJxI2S7t/qIFTHeJRYD7A9ykByaPRUaMKgw3G3eweHlWRWpB4t/kbt+MaJOesHEbC5brTWKxX4EOFfB8iFwltP8VWqyuoPXlkhuKgAaNJ+IeuihZtUUKHZYQ6MqNX4L6Q+4TOopyWI/XY/xYgJCJDojCrKEO0WguWPSG66BfZEQ830lY5kKXhHCG2iYkBRYlt398=,iv:J9fGe7b6GlBLq0RJV91vJo/2fJUmR96ORYdGuM6rqkI=,tag:CH4AqZWpkQghrDvoh6I8lw==,type:str]
    #ENC[AES256_GCM,data:mU6d3kAfZqRn470qxURIKLztq9jn4QBYHfWzzH/UUk2Hna3R3OEEgY5OSM40hGX+/OJxeuxC6IssYsfN4WNVBC3AnaWX,iv:ZpFfx+A6TXQ5fQ2jarh9193FF3HMp2Zmw7ah5w6w/J0=,tag:o4NaOpYaejkpzsYXknq5iQ==,type:comment]
    PROXIED: ENC[AES256_GCM,data:+VoWruw=,iv:IJLFJTSQjZE67G0U9K7A9TFMu34KVpQLsn88bb74j5Y=,tag:VnxtJ/+hkxBW9cT6Uv0NDA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0NXVySnRBMVkvMTFBbzFz
            ZEtoWTh2aFdyLzJlZ0lueThVTXltZkZTclJRCjFtWTdQZWppeS8yQTZPYW5zNXlj
            NXgrZVkzWmpleE1RSjhPb3pyNUFaUmsKLS0tIEFzQmt3bnFQdnVZRmdRbUhsMzN4
            V2pRbHdHSUxLSGRiT0h1Y2xsbkRud2sKAxceHQxR/d9QBDtYi/mQa0OIhA/ra2jO
            M3I73I0BYI5lqjbshzVf7dyapdLc4lQ8lOfABwZMvf3xb8CRAKN6cw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u897l89mkwn8jpwckjaln0fw50thp7mfs2c78cx0aw48slfyu5nsvvt4ft
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLTTlicjBuZC9ETEVORnFp
            ZWN2N1NCRU5xanU4UjBPMkx5bEFXZjFoV0RZCnRacU1BTVJrZlA5Mm1FUEZKK2JV
            Y0llK1VTVGdRbmRXMnJqZFl4YUJsQ1kKLS0tIHJvREw2OC9ObktKWjc1NkhaMVlo
            MjBoMHZ3bGw4OUxMVHhUS2U5KzBYd0kKzHyQXSPv0eobK4gb8DMNevWWAR4lYLD8
            ITXEim+3iKADgTWJ9n7tPzVV12v1wUMGy+k1Wj6ZuEZJJrcFrPC+kw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1gn97pnarxh3wkdv2l8ynk6s7ted0u5hgudhxyfec2djwy3dsapsss2ak8p
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBndjhUeG5ZWXZkNjExTmsw
            WlE1VlNyWUYwamJhOE5PUGN2eDhaYWJsRkdRCmYwQVRTUmU1dUhQT2Z1QWZLWFl4
            YVFlNzNTWm80OExYcGU5WkNXSkRpSDAKLS0tIEE4SVRpNHdkV3kyNDY5OUFEUU5E
            ZXlQRE1ZV1c5ZnQyckZQemYvQTRTczAKv6x8+JV3qNfz9svMtcqp63XNnoLOo7Tw
            cbJ3vs6N+wxQE2iJeqD6rbQeJ0/fWTDSJD+TJR5sIRGM5b0gP7DZ7g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1epz74rx38txrvhxxp4lq43lca6kg2yg0a5ay3pkhshfwgwx2dexsvj9vvz
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-24T20:25:38Z"
    mac: ENC[AES256_GCM,data:yPhOTqZt0rylH+ZjXWkFLygBQKFpOFGLQTn2WOxSFdYCd0XGZ9HV+reTIDDlqFZ3W9BS3hNUr8O8wOnKwwsx13O2T8fpDnLnD+9YCdmh/pfMLaPWayc/yEV4HX5i2QtaXfSUA/FuhFVP5qxAypL9Gmtq5NPV1qDqIXIqZnYAgyA=,iv:F1VdncrW+D6kCrPGmdgbcFwgE2uluLsCfejL7RnKlzM=,tag:HB39SVNnho9+r9aflrPStg==,type:str]
    version: 3.13.3
