apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns-secrets
    namespace: cloudflare-ddns
type: Opaque
stringData:
    #ENC[AES256_GCM,data:GOAuLY5FvR+sMHAWJZnzdMBPzLuAuBl4uITtiSGjIzMreJ0gtzfPoDVFhbQPFazc/kUt,iv:UIVwaKf/6T6w74B8k84Ye45bvnG1XwfmdbvXoy7IGHg=,tag:UTr/t/4WdDBa8YdN1TAJNw==,type:comment]
    CLOUDFLARE_API_TOKEN: ENC[AES256_GCM,data:RKfDOwHO1q8qYOCHoRLeof1Hz8CymDnqknvU9l2bRD4g0ciGZ3OvoA==,iv:rcq/mGZhSoF687EzALIBC4AZhGBJq6l4jsLVRyCtAsM=,tag:ZaP5X6YFAcc3XbFq8+oAbQ==,type:str]
    #ENC[AES256_GCM,data:2n3F9udyAQc3bajydZpamJZUB/3s1H218XSx7tODhyk7RFM0YoU4o8Sc,iv:6M2Cg9Z52gy138iSynpKsJSSV1M4qAg4OUiLL4GznSY=,tag:87CS00kTAbx+H2H0GhJ3tw==,type:comment]
    DOMAINS: ENC[AES256_GCM,data:VZ0/Htk3B7XFoScIv7qwyCjjtE1Z8tkToYUhaZM4+tp5obXouKmTZfBQ0YPRX7U8IaFoHd0tElp0uC493Lyt2Z2gAu+npov10mMhYg9oHPkpxJH4uBxllIUM83ceksnUVGiNveg2hNA5BJncFH85jXJfv4tRYvzf4z5Owz1fdFp4tor2tICOCwF1ETfO9315L1aplAwFZ5+bUZY42S75J6ZDwlw0YYXrOhFiybH84fezZsL6YMXcTs8XecoQuqDXKvY3gg90shXqIoKu5l4FZ/cwseEAdv/XJArdjPra3QM6PlJ/zPgcr/HmV/aOwOKjwxCEqRLzoPXcHfKonfJzYEpwi7Xw6yLgAiFRroCFMer+lCZcneNCNLG13KxYorQPSHPxfoc1OF0F5TIb2QYCzuJOlhq+gHUW4ouZm40p/ZV8yosiquLl5GAQTJufIsG5wqcWWmqok+J4jyT2LYhPP5jBJfs0lYM0D7J3TPNF9Ks0zpFszdVgb2g3fVl4xOEp1ogvuvoZQU5W7bdP40mjCyEXbg6YgrTsXDXreyK9XJzSwg2d7g/x5RBRhmGzUAnJqbyhrFeF0Qaoi/ZgCOEbwmRaX++Q7grEZf73bOgRzeWQpraDKL4qB6gQQXMf6I6kzTHhSoAwhZnLeWF5N2b3/EGraJOc0uiZJudXairC6cQ5Uz2Cuk4YTxGM52TPAdmha1m0GP2zsoZjpsMbflUg2mSop6XYoAmAQyJ4qzTE0keTKtDbbmX09JCPa6XFtAw0nljNxyJEmbsOfmCDwQF/2fovqx46+NQ+UD9dktZpgbSl7eb3cUAREUZavlcSwPmXpBCbWnx7nqx2BbNBHDyVReHxP1KqHZcr4uP+iDCieA16AFgdEAaroQDLSvOmoGF/m2yXVbsFAQoUfTdGwhzzqhnYW/oEjR3mD04Do6MyjpnaznLvZ0tQDYX4P/qsYtccDN+YOJWeBSPt98fiMw1NhRDSiPhsw+Fa92k0Jnx+jAl+mYUnGGxBa9/TKeTbIA==,iv:bQVCs1d0o3U0v0Kfgq9RPgcBMYjQT3x/29L/BXB4l6U=,tag:eq5RaxAjMkRCWr1kjL+NFg==,type:str]
    #ENC[AES256_GCM,data:mU6d3kAfZqRn470qxURIKLztq9jn4QBYHfWzzH/UUk2Hna3R3OEEgY5OSM40hGX+/OJxeuxC6IssYsfN4WNVBC3AnaWX,iv:ZpFfx+A6TXQ5fQ2jarh9193FF3HMp2Zmw7ah5w6w/J0=,tag:o4NaOpYaejkpzsYXknq5iQ==,type:comment]
    PROXIED: ENC[AES256_GCM,data:+VoWruw=,iv:IJLFJTSQjZE67G0U9K7A9TFMu34KVpQLsn88bb74j5Y=,tag:VnxtJ/+hkxBW9cT6Uv0NDA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0NXVySnRBMVkvMTFBbzFz
            ZEtoWTh2aFdyLzJlZ0lueThVTXltZkZTclJRCjFtWTdQZWppeS8yQTZPYW5zNXlj
            NXgrZVkzWmpleE1RSjhPb3pyNUFaUmsKLS0tIEFzQmt3bnFQdnVZRmdRbUhsMzN4
            V2pRbHdHSUxLSGRiT0h1Y2xsbkRud2sKAxceHQxR/d9QBDtYi/mQa0OIhA/ra2jO
            M3I73I0BYI5lqjbshzVf7dyapdLc4lQ8lOfABwZMvf3xb8CRAKN6cw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u897l89mkwn8jpwckjaln0fw50thp7mfs2c78cx0aw48slfyu5nsvvt4ft
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLTTlicjBuZC9ETEVORnFp
            ZWN2N1NCRU5xanU4UjBPMkx5bEFXZjFoV0RZCnRacU1BTVJrZlA5Mm1FUEZKK2JV
            Y0llK1VTVGdRbmRXMnJqZFl4YUJsQ1kKLS0tIHJvREw2OC9ObktKWjc1NkhaMVlo
            MjBoMHZ3bGw4OUxMVHhUS2U5KzBYd0kKzHyQXSPv0eobK4gb8DMNevWWAR4lYLD8
            ITXEim+3iKADgTWJ9n7tPzVV12v1wUMGy+k1Wj6ZuEZJJrcFrPC+kw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1gn97pnarxh3wkdv2l8ynk6s7ted0u5hgudhxyfec2djwy3dsapsss2ak8p
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBndjhUeG5ZWXZkNjExTmsw
            WlE1VlNyWUYwamJhOE5PUGN2eDhaYWJsRkdRCmYwQVRTUmU1dUhQT2Z1QWZLWFl4
            YVFlNzNTWm80OExYcGU5WkNXSkRpSDAKLS0tIEE4SVRpNHdkV3kyNDY5OUFEUU5E
            ZXlQRE1ZV1c5ZnQyckZQemYvQTRTczAKv6x8+JV3qNfz9svMtcqp63XNnoLOo7Tw
            cbJ3vs6N+wxQE2iJeqD6rbQeJ0/fWTDSJD+TJR5sIRGM5b0gP7DZ7g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1epz74rx38txrvhxxp4lq43lca6kg2yg0a5ay3pkhshfwgwx2dexsvj9vvz
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-26T03:45:51Z"
    mac: ENC[AES256_GCM,data:hUCV0BCj8/SZy5MtJ/V6H36rjcrFvDb7kOlrs7erYUrJzZULDH0pKGjCV16z1BoXP6Ffgg8TanMPb7y47nTyDHZp5UyUr5i7wOWA7tCeaUMTYvUu3OM/JaPBnR5KB1GZAcF0jZyo01J+AIikO7r1xkcfFehXAZd4NLnN0yQ845g=,iv:KJCYMaT63JFwR2oLwHtA74T9uWSYzUN9obTxFlTyRc4=,tag:n6c+LtD+9kBLi1Q3ecVW8g==,type:str]
    version: 3.13.3
