apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns-secrets
    namespace: cloudflare-ddns
type: Opaque
stringData:
    #ENC[AES256_GCM,data:GOAuLY5FvR+sMHAWJZnzdMBPzLuAuBl4uITtiSGjIzMreJ0gtzfPoDVFhbQPFazc/kUt,iv:UIVwaKf/6T6w74B8k84Ye45bvnG1XwfmdbvXoy7IGHg=,tag:UTr/t/4WdDBa8YdN1TAJNw==,type:comment]
    CLOUDFLARE_API_TOKEN: ENC[AES256_GCM,data:RKfDOwHO1q8qYOCHoRLeof1Hz8CymDnqknvU9l2bRD4g0ciGZ3OvoA==,iv:rcq/mGZhSoF687EzALIBC4AZhGBJq6l4jsLVRyCtAsM=,tag:ZaP5X6YFAcc3XbFq8+oAbQ==,type:str]
    #ENC[AES256_GCM,data:2n3F9udyAQc3bajydZpamJZUB/3s1H218XSx7tODhyk7RFM0YoU4o8Sc,iv:6M2Cg9Z52gy138iSynpKsJSSV1M4qAg4OUiLL4GznSY=,tag:87CS00kTAbx+H2H0GhJ3tw==,type:comment]
    DOMAINS: ENC[AES256_GCM,data:T4UpWSkNHT7Y/jlSNxDN2JKhcKm0wXyR2qsxM2nN41/+zClYIv+ObFvfIS3ZoCP58ATZNm6VtG77YivkW3Y2xsaLZTLIBX6zckPFtYnOoASrb2OsId+voomd9v/FzLyB3CODNXF1vxu8b34dpTZgnLI71nysOCXoG0Iu3+IZiWMDHbhyQqCmESwK/p2or/yrvOOq7UUlW+u0cPaENB2S2q6l3uz4cXbR069SE+1HWLkWfgxFMc0mEjCpBxG35x3ALbtqUOkY7iJ8JHUqvFJdw+tRpqQH/nf0RFXr9UUrdKI1zB/Dm5NHGDlXoZ4HVbRlsc9AgA5fJ2D3yJ3T1TtNa2m+swGe/kvxNk4TivF9k+Ch8l8RUXCxJ70KivHMU/R8Rld1AiXsWyHnhDGbaISO15sKu9ZUQUpaPh1fJAFCzNFCpkqZ200an+nyJ3dEmlLlUS2G7OTHT1wZf+Ls0twi5frdu1EGCxqVJ3g/0ciKGGz1zxVMGkVD/Q0k8RYZT0R9DN+NdYRlDL/onrSRo3CvM+rJgu8ea3Dy47NBnIvSY9XfiC57SnnDSVOhRkXKXwOWq5Cx8y8KLn2BeGaicVk9Y5eWsm6wRavMpPdzZmHIaq1ql0FODWCaKsXUSZu9t/cnym/24btpnB5qfLV6XtsQYqpKAi8JmLxZLdCtE/wskbQQMeeBbNLFa12cNytTZNykkdlu5x0n+9RAohDHDbtOt1teD4CxAf4KYBuU/rM7MVKzxH5C6nV4NrJ2W2SP/TTPAd31K/4ioDAGPNNT0TLyyZ6wbdgx6W52bHYH/WC+Ib0sd0FAGu/PH/D6q7Q4ckdP3xJ975WAmTyPf2oi1HXqaynE4D3+1gD8HMLaot12oxWYfPnd/3nIZLWggcroMmuid9Ib3UFhlL14rl91i1/ZwiqOvXWacDut6Q==,iv:NqEtOcGnLUd9gsd7IlZ3/xwLpzcGiawEWMOA5OJb6Mk=,tag:sxfVpFA7lucshWv1RLf2FA==,type:str]
    #ENC[AES256_GCM,data:mU6d3kAfZqRn470qxURIKLztq9jn4QBYHfWzzH/UUk2Hna3R3OEEgY5OSM40hGX+/OJxeuxC6IssYsfN4WNVBC3AnaWX,iv:ZpFfx+A6TXQ5fQ2jarh9193FF3HMp2Zmw7ah5w6w/J0=,tag:o4NaOpYaejkpzsYXknq5iQ==,type:comment]
    PROXIED: ENC[AES256_GCM,data:+VoWruw=,iv:IJLFJTSQjZE67G0U9K7A9TFMu34KVpQLsn88bb74j5Y=,tag:VnxtJ/+hkxBW9cT6Uv0NDA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0NXVySnRBMVkvMTFBbzFz
            ZEtoWTh2aFdyLzJlZ0lueThVTXltZkZTclJRCjFtWTdQZWppeS8yQTZPYW5zNXlj
            NXgrZVkzWmpleE1RSjhPb3pyNUFaUmsKLS0tIEFzQmt3bnFQdnVZRmdRbUhsMzN4
            V2pRbHdHSUxLSGRiT0h1Y2xsbkRud2sKAxceHQxR/d9QBDtYi/mQa0OIhA/ra2jO
            M3I73I0BYI5lqjbshzVf7dyapdLc4lQ8lOfABwZMvf3xb8CRAKN6cw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u897l89mkwn8jpwckjaln0fw50thp7mfs2c78cx0aw48slfyu5nsvvt4ft
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLTTlicjBuZC9ETEVORnFp
            ZWN2N1NCRU5xanU4UjBPMkx5bEFXZjFoV0RZCnRacU1BTVJrZlA5Mm1FUEZKK2JV
            Y0llK1VTVGdRbmRXMnJqZFl4YUJsQ1kKLS0tIHJvREw2OC9ObktKWjc1NkhaMVlo
            MjBoMHZ3bGw4OUxMVHhUS2U5KzBYd0kKzHyQXSPv0eobK4gb8DMNevWWAR4lYLD8
            ITXEim+3iKADgTWJ9n7tPzVV12v1wUMGy+k1Wj6ZuEZJJrcFrPC+kw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1gn97pnarxh3wkdv2l8ynk6s7ted0u5hgudhxyfec2djwy3dsapsss2ak8p
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBndjhUeG5ZWXZkNjExTmsw
            WlE1VlNyWUYwamJhOE5PUGN2eDhaYWJsRkdRCmYwQVRTUmU1dUhQT2Z1QWZLWFl4
            YVFlNzNTWm80OExYcGU5WkNXSkRpSDAKLS0tIEE4SVRpNHdkV3kyNDY5OUFEUU5E
            ZXlQRE1ZV1c5ZnQyckZQemYvQTRTczAKv6x8+JV3qNfz9svMtcqp63XNnoLOo7Tw
            cbJ3vs6N+wxQE2iJeqD6rbQeJ0/fWTDSJD+TJR5sIRGM5b0gP7DZ7g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1epz74rx38txrvhxxp4lq43lca6kg2yg0a5ay3pkhshfwgwx2dexsvj9vvz
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-22T20:58:39Z"
    mac: ENC[AES256_GCM,data:azqcNE9CFT7W6hEVveeuDlcJPtFAW7EFavLGWPQJ9DhDiGY7cmEvqM0SQPpSQ/qo93kvhCtzJ6NcgoXzti9r4ImdP6c7rP7QH3q4NP63eve852/Ghh30uBivsFmz5I9gqrprB9GtjSBX8NuX9O+k1kol8gDhnpul1y3av41Ah7s=,iv:tpCOKDIcziodCnFo0+NfXNpNUP6btNmBR+plfTbjntc=,tag:meT0Uuw7c9wDwzJwF2ZkWw==,type:str]
    version: 3.13.3
