apiVersion: v1
kind: Secret
metadata:
    name: tooltracker-secrets
    namespace: tooltracker
type: Opaque
stringData:
    #ENC[AES256_GCM,data:6CoeM5ACmJifvB6UPG6aBychsD5yJzic2ZZ24cX7Ulea+7eym/uuYZImc+xZZDZw/ZOsTbApQKtdCCvE2wZNFnfLMek0hWRy8Q53RQ==,iv:I6Q96ObHQVt+xzw+hy4ZOwSdkEHNXWxsSywIP5/X3nM=,tag:XVNdcW0UCrhke9zz2uKWiA==,type:comment]
    SECRET_KEY: ENC[AES256_GCM,data:Wgcwi8PM+tuaCQA8UX0MD7xHlDbSe/4pUknWeSE/+C3ZSKvOzRemSsQ/6X2BDQWl9JtfMMrMj9G9UkQIlFF/DA==,iv:bGVShiJSCmDHpTrBokPAsfxYciU6AtMrHLxv3aQtrAE=,tag:sqts21NBb7Qdlp8HdVWtmw==,type:str]
    #ENC[AES256_GCM,data:YqT1djIKkpvWcs/i9Qvks1Wm9HQILg==,iv:CNtEXyGDybdDbdRcoaJGHgopg6G5S1zdVwN1u0AnR+Q=,tag:ADy+HFPmC0jYNmSEsm/yCQ==,type:comment]
    OIDC_CLIENT_ID: ENC[AES256_GCM,data:eGJ/ah2dNzuMJIZgvFYb9Yk2xZwX8zSSPCpQKUSwfkhFxmZM,iv:oIhHIUGEOYOOpIpJjhtdwSi49uPusfQ5y1FtwlvzcDc=,tag:37fDrZBY8wN3CBohj+brMQ==,type:str]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:gCAZYDACEipp+iGXpuuhVrDqkBjAj5B1bP6M/WkZaFM=,iv:pvNtfZVlWOwbki8m8S1i+LaUDDn8FbVI2uFzJ9jvM4g=,tag:mc9UomoHkDhb9ZXdyPJrrQ==,type:str]
    #ENC[AES256_GCM,data:UQAtSmmQkzyO5HzB+YMwzJK3C2eaVF+ocNBxTD2GR5O+CkMRxV/7IEinzQ==,iv:uSgQxLaETCtHh/IocS66clbfoOWGZde9nuNl3KCxNKM=,tag:7+Qn47yeawByOvEeAcc2Xg==,type:comment]
    APP_URL: ENC[AES256_GCM,data:UY7yT6CS07fQwmzvf3OfBtTQFFOqZtIrOoRabfc=,iv:JFY5Eoqd6s4XKGmeZ0MDQlBzh74QmS6S7JtZhTZnItA=,tag:zhceD79PX157xsx72s6Frw==,type:str]
    OIDC_ISSUER: ENC[AES256_GCM,data:tEBU/BASzg0y4CkWihGUmHDWEmO33bpYIzUu,iv:QAPkk8IUCQ+9BgodvObQyaQqDehRoZarjm985Q9XRkA=,tag:ozPxq1pDcIcrt3WPIWL+XA==,type:str]
    OIDC_DISCOVERY_URL: ENC[AES256_GCM,data:6jg1wxLmmBjsa48Kda2NM89mlgo5hm4lXYjYsBM9wpuX3pAjsqcZpIZ5yJadW5hvnWV0ZKMffY5euCuq,iv:jSJ+11LDB62/GpcH63KA3mYjylEcBilPcH7X+QMu4OM=,tag:z90VlbP2Hae+rSWToZ1R+w==,type:str]
    OIDC_REDIRECT_URI: ENC[AES256_GCM,data:LwcjQmEnGri1SSU0HoaET19BWUlSi1mw4Mrcu+9DsoYtHVTFgLIrW8zKLQ==,iv:mDnJ0liisf6ZHrO1sfizsnmLRqG+hBjSsop9beCVftU=,tag:tAEePu03iGDdrrcUAEJ8Yg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZQk9CMElnU2x3YkxUN3Y5
            RzJweDN1NGI3VlFxTXhMUjNQN3ZXbTJNeUNRCkFqK2w3aDJDTEpOQU9MNHVTR2Mv
            bjZJcitIeUpzOG1MYmFPc1NhbWVqNDgKLS0tIG10b0Q5NEEwVGd3bnFyWEcvemdu
            SnYzYWM1cnVRT29vZE5QZnUwbnVrUDQKtzSvk1RJ9/uFdSLoM8NMMhpOVrf6yT3g
            6xlNoWH5WhhgfcQZRHrfZZiy4yPntcUjGKAqz2gZmxzAwzUDTnvHiw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u897l89mkwn8jpwckjaln0fw50thp7mfs2c78cx0aw48slfyu5nsvvt4ft
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPeExremszcXNWcWo3YzRL
            bW5na0tuazRCTmpJME96dHViSWlKVkwxaHo4Clg1NnBpcGhaWFVNclFlRnh2cXp6
            K1U1dFF2eDF5OWVKRnBYVjl6OFFvTFUKLS0tIG52TEhkN3czYWQxbUE3SUdQTDl4
            WlZkS3gvQXhGU3RWajRJWitVNlZiNEEKNsV1ynYRaWeob/YSThKiDER7+74CztIv
            jidJR+t//x2Sk0Hgmn1/INeUJipMYYwLJc5XEYd6X5kYq0Qr5AMrsw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1gn97pnarxh3wkdv2l8ynk6s7ted0u5hgudhxyfec2djwy3dsapsss2ak8p
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2dWo0RCtxUHNTWW9HK3lr
            dFpsVy9VcVQ5bm5EUnFyRUJ6YTgrSkNlN1hJCmxRTUsvKzFYbjZYUEU1WUU5d2JC
            NkM2SnZ4Tk5TS05TMk9WU2VjVy9LOTAKLS0tIHRkVjlPUHNkZW1say9OdWlrSXJH
            M29QSVduMlZBMTNRSVlCNCtMSXRLTjQK8PzHq4hZe2zlr1+ZGfePpNWgbztyhyIF
            9sS6Um4/4OPJAnWB5GcJuBv3aiLRtVA2zlFYX3BLjoHVEM90/uhkBA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1epz74rx38txrvhxxp4lq43lca6kg2yg0a5ay3pkhshfwgwx2dexsvj9vvz
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-22T21:27:14Z"
    mac: ENC[AES256_GCM,data:OJnoRHSARTYKOfERJFUYCvJciinF1J3Td3cnNb0ij2yjARsjLjaVDw5iLnigX6Akux5XTytB29BVan26Bo+Fk3SVT6Od82jHdRadlhD44SI/qZaUafCx77S5iHz7+errvAlciFhN2GNIuoQ7CGYzSeTiG+otW0aItQ7CbDnhDkc=,iv:9z6ajJi4EuZ3EICLnyJJ7a9HGELoMLskZI+oohsEkdI=,tag:X6k3bLd/ULZCNGTvhvydXA==,type:str]
    version: 3.13.3
