apiVersion: v1
kind: Service
metadata:
  name: dawarich
  namespace: dawarich
  labels:
    app: dawarich
spec:
  type: ClusterIP
  selector:
    app: dawarich
    app.kubernetes.io/name: dawarich
  ports:
    - name: http
      port: 3000
      targetPort: http
      protocol: TCP
